version: "3.8"

services:
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    environment:
      DIRECTUS_SECRET: your-secret-key
      DATABASE_CLIENT: sqlite3
      DATABASE_FILENAME: /data/db.sqlite
    volumes:
      - directus_data:/data
    restart: always

  vite:
    build: ./
    container_name: vite-app
    environment:
      - VITE_API_URL=http://localhost:8055
    ports:
      - "3000:4173"
    restart: always

volumes:
  directus_data:
  vite_data:
